name: Setup Node
description: Node(+pnpm)環境をセットアップする Composite Action

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --ignore-scripts
